# fly.toml app configuration file generated for rublevsky-studio-laravel on 2024-10-10T14:18:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rublevsky-studio-laravel'
primary_region = 'yyz'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  R2_ACCESS_KEY = "${R2_ACCESS_KEY}"
  R2_SECRET_KEY = "${R2_SECRET_KEY}"
  R2_BUCKET = "${R2_BUCKET}"
  R2_ENDPOINT = "${R2_ENDPOINT}"
  R2_REGION = "${R2_REGION}"
  R2_URL = "${R2_URL}"
  FILESYSTEM_DISK = 'public'
  STRIPE_SECRET = "${STRIPE_SECRET}"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "storage_vol"
  destination = "/var/www/html/storage_"
