# fly.toml app configuration file generated for rublevsky-studio on 2024-10-24T14:10:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rublevsky-studio'
primary_region = 'yyz'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  ADMIN_EMAIL = 'alexander.rublevskii@gmail.com'
  APP_ENV = 'production'
  APP_NAME = 'Rublevsky Studio'
  APP_URL = 'https://www.rublevsky.studio/'
  FILAMENT_FILESYSTEM_DISK = 'r2'
  FILESYSTEM_DISK = 'r2'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  MAIL_FROM_ADDRESS = 'alexander@rublevsky.studio'
  MAIL_FROM_NAME = 'Rublevsky Store'
  MAIL_MAILER = 'resend'
  QUEUE_CONNECTION = 'database'
  R2_ACCESS_KEY = '${R2_ACCESS_KEY}'
  R2_BUCKET = 'rublevsky-studio-storage'
  R2_ENDPOINT = 'https://your-endpoint.r2.cloudflarestorage.com'
  R2_REGION = 'auto'
  R2_SECRET_KEY = '${R2_SECRET_KEY}'
  R2_URL = 'https://pub-e0cacce632b34b06ae852d50afaa9085.r2.dev'
  RESEND_KEY = '${RESEND_KEY}'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  STRIPE_SECRET = '${STRIPE_SECRET}'

[processes]
  app = ''
  worker = 'php artisan queue:listen'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


